### ISSUE TITLE
Serious compatibility problem with Thermal Foundation and TFC-Metallum

### ISSUE THREAD

**Issue by MasterIMLG** [Mrthomas20121/TinkerFirmaCraft#14]
**Describe the bug/crashreport**
While melting redstone, glowstone, ender pearls and Pyrotheum, Cryotheum, Aerotheum, Petrotheum from Thermal Foundation, it always melted into Pig Iron of TFC instead.
So does the Tungsten or any other metals or alloys from TFC-Metallum.

**To Reproduce**
Put redstone dust etc. and any metal ingot from TFC-Metallum into smeltery.

**Expected behavior**
Redstone dust should be melted into destabilized redstone fluid.
Glowstone dust shoulde be melted into Energized Glowstone fluid.
Ender Pearls shoulde be melted into Resonant Ender fluid.
Pyrotheum dust should be melted into Blazing Pyrotheum fluid.
Cryotheum dust shoulde be melted into Gelid Cryotheum fluid.
Aerotheum dust shoulde be melted into Zephyrean Aerotheum fluid.
Petrotheum dust shoulde be melted into Tectonic Petrotheum fluid.
Other metal ingots should be melted into corresponding liquid metal.

**Screenshots**
No specific screenshots.

**Crash report Link**
No crash report, this bug didn't cause the client to crash.

**Version**
 - Minecraft: :1.12.2
 - TinkerFirmaCraft :tfc_tinkers-1.5.0
 - Forge :1.12.2-forge-14.23.5.2854
 - TerraFirmaCraft:TerraFirmaCraft-MC1.12.2-1.7.10.168
 - Tinker's Construct:TConstruct-1.12.2-2.13.0.183

**Additional mods involved**
ThermalFoundation-1.12.2-2.6.7.1-universal
TFC-Metallum-MC1.12.2-1.4.0
TinkersComplement-1.12.2-0.4.3
plustic-8.0.1.0
conarm-1.12.2-1.2.5.9
armoryexpansion-1.4.2

Perhaps anything thrown in will be melted into Pig Iron? I haven't tested this bug thoroughly, other materials could be the same.

**Comment by Mrthomas20121** [comment]
have you tried with just thermal foundation tfc, tfc metallum and tfc tinker?

**Comment by Mrthomas20121** [comment]
It work just fine with thermal foundation, tfc tinkers and tfc metallum.
![image](https://user-images.githubusercontent.com/34064092/102699628-77346b00-4246-11eb-8e9a-a29431ee4fbd.png)

**Comment by Mrthomas20121** [comment]
plustic might be the cause.

**Comment by Mrthomas20121** [comment]
i figured what was the problem. should be fixed asap

**Comment by MasterIMLG** [comment]
Since TConstruct have no update since March, would you please register smeltery recipe for Pyrotheum etc. while fixing this bug? 
Mean while, I'll test this bug further to see if I can provide you more helpful intel. Thanks for you mod anyway!

**Comment by MasterIMLG** [comment]
Sorry to forgot mentioning that I used Blazing Pyrotheum as smeltery fuel which REQUIRES PlusTiC to support.
And this bug still exist without PlusTiC.

**Comment by Mrthomas20121** [comment]
you don't need to test anything i know what's wrong.

**Comment by Mrthomas20121** [comment]
![image](https://user-images.githubusercontent.com/34064092/102709434-e774d800-42aa-11eb-8ba5-daa774faa7ba.png)
it's fixed now
